### ISSUE TITLE
Write up the algorithms

### ISSUE THREAD

**Issue by domoritz** [domoritz/draco#13]

**Comment by Mestway** [comment]
We will use the discriminative learning to train our Markov net. 
(https://homes.cs.washington.edu/~pedrod/papers/aaai05.pdf)

Given a training pair (x,y) where x is a partial spec and y is the ground truth full spec. For the i-th soft constraint, the gradient for its weight `w_i` would be `n_i(x, y) - n_i(x, y*)`, where y* is the MAP inference result for x. (The MAP inference result y* is obtained by solving the partial spec using current weight given x.)

`n_i(x, y)` is the number of groundings that satisfies the i-th soft constraint. 

Thus, we need to have a function to return the number of satisfied groundings for each soft constraint in our constraint system.

Can you help write a function `count_true_groundings(i, full_spec)` to return to total number of truth groundings for the i-th soft constraint?

Thanks!

**Comment by domoritz** [comment]
I moved this over to HackMD so we can have inline latex: https://hackmd.io/s/H1RYJ5RRW.
