### ISSUE TITLE
remove scale

### ISSUE THREAD

**Issue by domoritz** [domoritz/draco#15]

**Comment by Mestway** [comment]
What are other things we need to include after removing scale?

**Comment by domoritz** [comment]
For now log and zero.

**Comment by domoritz** [comment]
@Mestway removed scales in 9813f75bcfeceab3467e703322c2f236a95112d6. 

Still need to add support for zero and log to close this issue.

**Comment by domoritz** [comment]
See https://vega.github.io/vega-lite/docs/scale.html
