### ISSUE TITLE
Use clyngor

### ISSUE THREAD

**Issue by domoritz** [domoritz/draco#19]

**Comment by Mestway** [comment]
Looks like a beta library?

**Comment by domoritz** [comment]
I'm making the transition now and it's really nice. They take care of the parsing the output and running the command.

**Comment by Mestway** [comment]
I see, so the idea is that we no longer need to use sub-process to call clingo? (Since there would already be a built-in wrapper)

**Comment by domoritz** [comment]
Done in bafb338c5deeed677b934cf840bda6b9a9f2a088
