### ISSUE TITLE
Fix outputs

### ISSUE THREAD

**Issue by domoritz** [domoritz/draco#3]
For example, `bin: 3` is not valid.

**Comment by Mestway** [comment]
Fixed bins and current ones look pretty good already.

**Comment by domoritz** [comment]
What about log scales and zero scales? Also, builds are failing now.

**Comment by Mestway** [comment]
Builds looks fine. I tried to write a test using jsonvalidate package from pip to validate generated vegalite specs, but somehow it always shows validation failed. 

Is the schema https://vega.github.io/schema/vega-lite/v2.0.json the one we want to validate against?

**Comment by domoritz** [comment]
I'd validate against the schema in `node_modules/vega-lite/build/vega-lite-schema.json`. 

Ignore my comment about builds failing.
