### ISSUE TITLE
Write tests for python code

### ISSUE THREAD

**Issue by domoritz** [domoritz/draco#4]

**Comment by domoritz** [comment]
I added coverage reports to make it easy to track what we are testing: https://cover
alls.io/github/domoritz/draco?branch=master

**Comment by Mestway** [comment]
Would add test for checking output json files conform Vega-Lite schema later.

**Comment by domoritz** [comment]
Yes, I was thinking about that as well. I think that's orthogonal to unit tests, though.

**Comment by domoritz** [comment]
We added schema tests.
