### ISSUE TITLE
Hard constraints

### ISSUE THREAD

**Issue by domoritz** [domoritz/draco#52]
* [x] Don't use bar with just d
* [x] Don't use rule with only x or y
* [x] rule and tick need q
* [ ] do not use negative values for size
* [x] size should have high preference for zero, even with bin
* [x] don't allow row without y, column without x
* [x] stack can only have one continuous and it has to be on x or y
* [x] only allow dates to be used for temporal (no string or number)
* [x] we overlap bars when we don't have an ordinal and only q

**Comment by haldenl** [comment]
There might be a bug in `test.lp` with `stack`.

stacking opacity works, e.g.:

```
{
    'mark': 'bar',
    'encoding': {
        'x': {
            'type': 'nominal',
            'field': 'n1',
        },
        'y': {
            'type': 'quantitative',
            'field': 'q1',
            'stack': 'zero',
            'aggregate': 'sum'
        },
        'opacity': {
            'type': 'quantitative',
            'field': 'q2'
        }
    }
}
```

But stacking color does not:

```
{
    'mark': 'bar',
    'encoding': {
        'x': {
            'type': 'nominal',
            'field': 'n1',
        },
        'y': {
            'type': 'quantitative',
            'field': 'q1',
            'stack': 'zero',
            'aggregate': 'sum'
        },
        'color': {
            'type': 'quantitative',
            'field': 'q2'
        }
    }
}
```

I included an additional test case in `tests/generate/test_gen_helper.py` for the `color` case.

I was poking around test.lp and the problematic lines seem to be 

```
131:  % stack if no opacity is used for bar and area
132:  :- not channel(_,opacity), mark(bar;area), channel(_,(detail;color;opacity)), not stack(_).
```

**Comment by domoritz** [comment]
fixed the last bug
