### ISSUE TITLE
Build for the web

### ISSUE THREAD

**Issue by domoritz** [domoritz/draco#66]
Run clingo in browser: https://potassco.org/clingo/run/

Building for the web: https://github.com/potassco/clingo/issues/90

I’d like to use wasm instead of compiling to JavaScript. Here are instructions: https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm. I think all we need to do is pass `WASM=1` to `emcc`.

**Comment by domoritz** [comment]
We also want to be able to take the output from clingo and generate a Vega-Lite spec.

**Comment by haldenl** [comment]
move .lp files into .ts variables.

**Comment by haldenl** [comment]
use weights.json for weight definitions
